backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "landing"
    label: "Landing"
    files:
      - name: "home"
        label: "Home"
        file: "src/content/landing/home.json"
        format: "json"
        fields:
          - label: "Full Width Card"
            name: "fullWidthCard"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Headline", name: "headline", widget: "text", hint: "Use a line break for DECK / PACKAGES" }
              - { label: "Body", name: "body", widget: "text" }
              - label: "Icons (2)"
                name: "icons"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Alt", name: "iconAlt", widget: "string", required: false }

          - label: "Three Columns Cards"
            name: "threeColumnsCards"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Items (3)"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Body", name: "body", widget: "text" }
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Alt", name: "iconAlt", widget: "string", required: false }
